version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

services:
  nginx:
    image: moodletw/${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_DATA_PATH_HOST}:${APP_DATA_PATH_CONTAINER}
    ports:
      - "${HTTP_PORT_HOST}:8080"
    networks:
      backend:
        aliases:
          - ${APP_HOST}

  php-fpm:
    image: moodletw/${COMPOSE_PROJECT_NAME}-php-fpm
    restart: always
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_DATA_PATH_HOST}:${APP_DATA_PATH_CONTAINER}
      - ${APP_PHP_CONF_PATH_HOST}:/usr/local/etc/php-fpm.d
    networks:
      - backend

  workspace:
    image: moodletw/${COMPOSE_PROJECT_NAME}-workspace
    restart: always
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_DATA_PATH_HOST}:${APP_DATA_PATH_CONTAINER}
    ports:
      - "${WORKSPACE_HOST_SSH_PORT}:22"
    networks:
      - backend

  agent:
    image: zabbix/zabbix-agent
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_DATA_PATH_HOST}:${APP_DATA_PATH_CONTAINER}
    environment:
      - TZ=${TIMEZONE}
      - ZBX_HOSTNAME=${COMPOSE_PROJECT_NAME}
      - ZBX_STARTAGENTS=0
      - ZBX_PASSIVE_ALLOW=false
      - ZBX_ACTIVE_ALLOW=true
      - ZBX_ACTIVESERVERS=${ZBX_ACTIVESERVER}
      #- ZBX_DEBUGLEVEL=4
    networks:
      - backend